XeniaBot.WebPanel/Models/Pages/NotAuthorizedViewModel.cs
namespace XeniaBot.WebPanel.Models;

public class NotAuthorizedViewModel
{
    public string? Message { get; set; }
    public bool ShowLoginButton { get; set; }

    public NotAuthorizedViewModel()
    {
        ShowLoginButton = false;
    }
}

XeniaBot.WebPanel/Models/Pages/NotFoundViewModel.cs
namespace XeniaBot.WebPanel.Models;

public class NotFoundViewModel
{
    public string Message { get; set; }

    public NotFoundViewModel()
    {
        Message = "";
    }
}

XeniaBot.WebPanel/Controllers/AuthenticationController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using XeniaBot.WebPanel.Extensions;

namespace XeniaBot.WebPanel.Controllers;

public class AuthenticationController : Controller
{
    [HttpGet("~/signin")]
    public async Task<IActionResult> SignIn() => View("SignIn", await HttpContext.GetExternalProvidersAsync());

    [HttpPost("~/signin")]
    public async Task<IActionResult> SignIn([FromForm] string provider, string redirect = "/")
    {
        // Note: the "provider" parameter corresponds to the external
        // authentication provider choosen by the user agent.
        if (string.IsNullOrWhiteSpace(provider))
        {
            return BadRequest();
        }

        if (!await HttpContext.IsProviderSupportedAsync(provider))
        {
            return BadRequest();
        }

        var parsedUri = new Uri("https://xb.kate.pet" + redirect);
        redirect = parsedUri.PathAndQuery;

        // Instruct the middleware corresponding to the requested external identity
        // provider to redirect the user agent to its own authorization endpoint.
        // Note: the authenticationScheme parameter must match the value configured in Startup.cs
        return Challenge(new AuthenticationProperties { RedirectUri = redirect }, provider);
    }

    [HttpGet("~/signin/discord")]
    public async Task<IActionResult> SignInDiscord(string redirect = "/")
    {
        string provider = "Discord";
        // Note: the "provider" parameter corresponds to the external
        // authentication provider choosen by the user agent.
        if (string.IsNullOrWhiteSpace(provider))
        {
            return BadRequest();
        }

        if (!await HttpContext.IsProviderSupportedAsync(provider))
        {
            return BadRequest();
        }

        var parsedUri = new Uri("https://xb.kate.pet" + redirect);
        redirect = parsedUri.PathAndQuery;

        // Instruct the middleware corresponding to the requested external identity
        // provider to redirect the user agent to its own authorization endpoint.
        // Note: the authenticationScheme parameter must match the value configured in Startup.cs
        return Challenge(new AuthenticationProperties { RedirectUri = redirect }, provider);
    }

    [HttpGet("~/signout")]
    [HttpPost("~/signout")]
    public IActionResult SignOutCurrentUser()
    {
        // Instruct the cookies middleware to delete the local cookie created
        // when the user agent is redirected from the external identity provider
        // after a successful authentication flow (e.g Google or Facebook).
        return SignOut(new AuthenticationProperties { RedirectUri = "/" },
            CookieAuthenticationDefaults.AuthenticationScheme);
    }
}

XeniaBot.WebPanel/ViewComponents/NavbarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace XeniaBot.WebPanel.ViewComponents;

public class NavbarViewComponent : ViewComponent
{
    /// <summary>
    /// Only generate the option elements for a select.
    /// </summary>
    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View("Default");
    }
}

XeniaBot.WebPanel/Views/Shared/NotAuthorized.cshtml
@model NotAuthorizedViewModel?
@namespace XeniaBot.WebPanel.Views.Shared
@{
    ViewData["Title"] = "Not Authorized";
    Layout = "_Layout";
}

<h1>Unauthorized</h1>
<p>You cannot access this page due to you not being logged in or you don't have the right permissions.</p>
@if (@Model != null)
{
    <hr class="mt-2" />
    @if (@Model.ShowLoginButton)
    {
        <a class="btn btn-success" asp-area="" asp-controller="Authentication" asp-action="SignInDiscord" asp-route-redirect="@Context.Request.Path">Login</a>
    }
    <hr class="mb-2" />
    @if (!string.IsNullOrEmpty(@Model.Message))
    {
        <p>@Model.Message</p>
    }
}
<h4><a asp-area="" asp-controller="Home" asp-action="Index">Go Home</a></h4>

XeniaBot.WebPanel/Views/Shared/NotFound.cshtml
@model string

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h1>Not Found</h1>
<p>The data you requested could not be found. </p>
<pre><code>@Model</code></pre><br/>
<h4><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></h4>

XeniaBot.WebPanel/Views/Shared/_Layout.cshtml
@using XeniaBot.WebPanel.Helpers
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/" />
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Xenia Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="~/lib/jquery-datatables/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css"/>
    @* <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" /> *@
    <script src="~/lib/htmx.min.js" type="text/javascript"></script>
</head>
<body>
<header>
    @await Component.InvokeAsync("Navbar")
</header>
<div class="container">
    <main role="main" class="pb-3">
        @if (@Model != null)
        {
            if (typeof(BaseViewModel).IsAssignableFrom(@Model.GetType()) || @Model.GetType() == typeof(BaseViewModel))
            {
                if (@Model.Message != null)
                {
                    <div class="alert alert-@Model.MessageType mt-3" role="alert">
                        @Model.Message
                    </div>
                }
            }
        }
        @RenderBody()
    </main>
</div>
<footer class="border-top footer text-muted mt-4">
    <div class="container mt-3">
        &copy; 2023 - @DateTime.Now.Year - Xenia Bot & Dashboard Contributors - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a href="https://xenia.kate.pet">Website</a><br/>
        <hr/>
        @{
            var versionString = Program.Version?.ToString();
            if (versionString != null)
            {
                while (versionString.EndsWith(".0"))
                    versionString = versionString[..^2];
                if (!string.IsNullOrEmpty(versionString))
                {
                    versionString = $"v{versionString}";
                }
            }
        }
        <code>Xenia Dashboard @versionString</code>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@* <script src="~/lib/jquery-ui/jquery-ui.min.js"></script> *@
<script src="~/lib/jquery-datatables/datatables.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/select2/js/select2.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
@* <script src="~/_framework/blazor.server.js"></script> *@
</body>
</html>