XeniaBot.WebPanel/Controllers/WarnSystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using XeniaBot.Data.Repositories;
using XeniaBot.Data.Models;
using XeniaBot.Data.Services;
using XeniaBot.Shared;
using XeniaBot.WebPanel.Helpers;
using XeniaBot.WebPanel.Models;

namespace XeniaBot.WebPanel.Controllers;

[Controller]
public class WarnSystemController: BaseXeniaController
{
    private readonly ILogger<ServerController> _logger;

    public WarnSystemController(ILogger<ServerController> logger)
        : base()
    {
        _logger = logger;
    }

    public async Task<WarnGuildDetailsViewModel> GetDetails(ulong serverId)
    {
        var data = new WarnGuildDetailsViewModel();
        var guild = _discord.GetGuild(serverId);
        data.User = guild.GetUser(AspHelper.GetUserId(HttpContext) ?? 0);
        
        await AspHelper.FillServerModel(serverId, data);
        
        return data;
    }
    
    [HttpGet("~/Warn/Guild/{id}")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> GuildWarns(ulong id, string? messageType = null, string? message = null, bool newer_than_enable = false, string? newer_than = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = _discord.GetUser((ulong)userId);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;

        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;

        data.EnableNewerThanFilter = newer_than_enable;
        if (newer_than != null)
            data.NewerThanDate = newer_than;

        return View("Details", data);
    }
    
    [HttpGet("~/Warn/Info/{id}")]
    [AuthRequired]
    public async Task<IActionResult> WarnInfo(string id, string? messageType = null, string? message = null)
    {
        var controller = Program.Core.GetRequiredService<GuildWarnItemRepository>();
        var warnData = await controller.GetItemsById(id);
        if (warnData == null)
            return View("NotFound");

        var latestWarnData = warnData.FirstOrDefault();
        
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var guild = _discord.GetGuild(latestWarnData?.GuildId ?? (ulong)0);
        if (guild == null)
            return View("NotFound", "Guild not found");
        
        var data = new WarnInfoViewModel()
        {
            Guild = guild,
            WarnItem = latestWarnData,
            History = warnData
        };
        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;

        return View("Info", data);
    }

    [HttpGet("~/Warn/Guid/{id}/CreateWizard")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> CreateWarnWizard(ulong id, string? messageType = null, string? message = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = _discord.GetUser((ulong)userId);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);
        
        var data = await GetDetails(guild.Id);
        data.User = guildUser;

        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;

        return View("CreateWarnWizard", data);
    }

    [HttpPost("~/Warn/Guid/{id}/Create")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> CreateWarn(ulong id, string user, string reason)
    {
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");

        ulong userId = 0;
        try
        {
            if (!ulong.TryParse(user, out userId))
                throw new ArgumentException($"Failed to parse value \"{user}\"", nameof(user));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to create warn in Guild {GuildId} for User {UserId} (reason={Reason})",
                id, user, reason);
            return await CreateWarnWizard(id,
                messageType: "danger",
                message: $"Failed to create record. Failed to parse userId:  {ex.Message}");
        }

        try
        {
            var controller = Program.Core.GetRequiredService<WarnService>();
            var data = await controller.CreateWarnAsync(
                id, 
                userId, 
                AspHelper.GetUserId(HttpContext) ?? 0,
                reason);
            return RedirectToAction(
                "WarnInfo", new Dictionary<string, object>()
                {
                    {
                        "id", data.WarnId
                    }
                });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to create warn in Guild {GuildId} for User {UserId} (reason={Reason})",
                id, user, reason);
            return await CreateWarnWizard(id,
                messageType: "danger",
                message: $"Failed to create record. {ex.Message}");
        }
    }
}

XeniaBot.WebPanel/ViewComponents/UserSelectViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using XeniaBot.WebPanel.Models;

namespace XeniaBot.WebPanel.ViewComponents;

public class UserSelectViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(UserSelectModel data)
    {
        return View("Default", data);
    }
}

XeniaBot.WebPanel/Views/WarnSystem/CreateWarnWizard.cshtml
@using kate.shared.Helpers
@using XeniaBot.WebPanel.Helpers
@model WarnGuildDetailsViewModel

@{
    ViewBag.Title = $"{Model.Guild.Name} - Create Warn";
    Layout = "_Layout";
}


<h1>Create Warn</h1>
<form id="create_warn" enctype="application/x-www-form-urlencoded" method="post" asp-controller="WarnSystem" asp-action="CreateWarn" asp-route-id="@Model.Guild.Id">
    @await Component.InvokeAsync("UserSelect", new UserSelectModel()
    {
        Users = StrippedUser.FromGuild(Model.Client, Model.Guild),
        SelectedUserId = null,
        ParentFormId = "create_warn",
        Id = "create_warn_user",
        Name = "user",
        DisplayName = "Target User",
        Required = true
    })
    
    <div class="form-group mb-3">
        <label for="create_warn_reason">Reason</label>
        <textarea class="form-control" id="create_warn_reason" name="reason" rows="5" required></textarea>
    </div>
    
    <input class="btn btn-success" type="submit" value="Submit"/>
</form>

@section Scripts
{
    <script type="text/javascript">
        $("#create_warn_user").select2({
            minimumResultsForSearch: 5
        });
    </script>
}

XeniaBot.WebPanel/Views/WarnSystem/Details.cshtml
@using kate.shared.Helpers
@using System.Collections.Generic
@using XeniaBot.WebPanel.Models
@using XeniaBot.WebPanel.Helpers
@model WarnGuildDetailsViewModel

@{
    ViewBag.Title = $"{Model.Guild.Name} - Warns";
    Layout = "_Layout";
}

@await Component.InvokeAsync("GuildBanner", new GuildBannerViewParameters(Model.Guild.Id, true,
new List<BreadcrumbItem>()
{
    new BreadcrumbItem("Servers", "Server", "List"),
    new BreadcrumbItem(Model.Guild.Name, "Server", "Index", new Dictionary<string, string>()
    {
        {"id", Model.Guild.Id.ToString()}
    }),
    new BreadcrumbItem("Warns")
}))

<a class="btn btn-outline-primary btn-sm mb-2" asp-area="" asp-route-id="@Model.Guild.Id" asp-controller="Server" asp-action="Index">Go Back</a>
@if (Model.WarnItems.Any())
{
    <a class="btn btn-success btn-sm mb-2" asp-controller="WarnSystem" asp-action="CreateWarnWizard" asp-route-id="@Model.Guild.Id">
        <i class="bi bi-plus"></i>
    </a>
}
@* <form id="apply_filter" enctype="application/x-www-form-urlencoded" method="get" asp-controller="WarnSystem" asp-action="GuildWarns" asp-route-id="@Model.Guild.Id"> *@
@*     <div class="form-group form-inline"> *@
@*         <input class="form-check-input" type="checkbox" value="" name="newer_than_enable" @(Model.EnableNewerThanFilter ? "checked" : "") /> *@
@*         <label class="form-check-label mr-2" for="newer_than">Filter Results Newer than</label> *@
@*         <input class="form-control form-control-sm" type="text" id="newer_than" name="newer_than" value="@Model.NewerThanDate" /> *@
@*         <button class="ml-3 btn btn-sm btn-success" type="submit"> *@
@*             <i class="bi bi-check"></i> *@
@*         </button> *@
@*     </div> *@
@* </form> *@

@if (!@Model.WarnItems.Any())
{
    <div class="px-4 py-5 my-5 text-center">
        <h4>No Warn Records Found</h4>
        <p>There were no warn records found for this guild.</p>
        
        <a class="btn btn-success pt-3" asp-controller="WarnSystem" asp-action="CreateWarnWizard" asp-route-id="@Model.Guild.Id">
            Create Warn
        </a>
    </div>
}
else
{
    <table class="table" id="warnSystemGuildList" data-order='[[ 2, "dec" ]]'>
        <thead>
        <tr>
            <th>Target User</th>
            <th>Who Warned Them</th>
            <th>When</th>
            <th>Description</th>
            <th>
            </th>
        </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.WarnItems.OrderBy(v => v.CreatedAtTimestamp))
            {
                <tr>
                    <td>
                        <img src="@(AspHelper.GetUserProfilePicture(item.TargetUserId))" class="card-img-top smallUserIcon" />
                        @(Model.Client.GetUser(item.TargetUserId)?.ToString() ?? "unknown")
                    </td>
                    <td>
                        <img src="@(AspHelper.GetUserProfilePicture(item.ActionedUserId))" class="card-img-top smallUserIcon" />
                        @(Model.Client.GetUser(item.ActionedUserId)?.ToString() ?? "unknown")
                    </td>
                    <td>
                        @(AspHelper.DateTimeFromTimestamp(item.CreatedAtTimestamp).ToString("yyyy/MM/dd HH:mm:ss tt"))
                    </td>
                    <td>
                        <code>
                            @item.Description.Substring(0, Math.Min(50, item.Description.Length))
                            @if (@item.Description.Length > 50)
                            {
                                <span>...</span>
                            }
                        </code>
                    </td>
                    <td>
                        <a class="btn btn-secondary btn-sm" asp-area="" asp-route-id="@item.WarnId" asp-controller="WarnSystem" asp-action="WarnInfo"><i class="bi bi-info"></i></a>
                        @if (!Model.IsWarnActive(item))
                        {
                            <br>
                            <small class="text-muted">Inactive</small>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-outline-primary btn-sm" asp-area="" asp-route-id="@Model.Guild.Id" asp-controller="Server" asp-action="Index">Go Back</a>
    <a class="btn btn-success btn-sm" asp-controller="WarnSystem" asp-action="CreateWarnWizard" asp-route-id="@Model.Guild.Id">
        <i class="bi bi-plus"></i>
    </a>
}

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#warnSystemGuildList').DataTable({
                "searching": true
            });
            $('.dataTables_length').addClass('bs-select');
            
            $("#newer_than").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
        
    </script>
}

XeniaBot.WebPanel/Views/WarnSystem/Info.cshtml
@{
    Layout = "_Layout";

    string GetAvatar(string userId)
    {
        var a = "/Debugempty.png";
        if (string.IsNullOrEmpty(userId))
            return a;
        var u = Model.Client.GetUserAsync(ulong.Parse(userId)).Result;
        if (u != null)
        {
            var x = u.GetAvatarUrl();
            x ??= u.GetDefaultAvatarUrl();
            a = x;
        }

        return a;
    }

}
@using XeniaBot.WebPanel.Helpers
@model WarnInfoViewModel

<div class="container">
    <h1 class="mb-0">Warn Details</h1>
    <sup>@Model.WarnItem.WarnId</sup>
    <p>
        
        <img src="@GetAvatar(Model.WarnItem.TargetUserId.ToString())" class="smallUserIcon"/>
        <code alt="@Model.WarnItem.TargetUserId">@(Model.Client.GetUser(Model.WarnItem.TargetUserId)?.ToString() ?? Model.WarnItem.TargetUserId.ToString())</code>
        was warned by
        <img src="@GetAvatar(Model.WarnItem.ActionedUserId.ToString())" class="smallUserIcon"/>
        <code alt="@Model.WarnItem.ActionedUserId">@(Model.Client.GetUser(Model.WarnItem.ActionedUserId)?.ToString() ?? Model.WarnItem.ActionedUserId.ToString())</code>
        at
        <code>@(AspHelper.DateTimeFromTimestamp(Model.WarnItem.CreatedAtTimestamp).ToString("yyyy/MM/dd HH:mm:ss tt"))</code>
        in
        <a asp-controller="Server" asp-route-id="@Model.Guild.Id" asp-action="Index"><code>@Model.Guild.Name</code></a>
    </p>
    <h4>Description</h4>
    <textarea class="form-control" readonly rows="15">@Model.WarnItem.Description</textarea>
    <a class="btn btn-outline-primary btn-sm mt-3" asp-controller="WarnSystem" asp-action="GuildWarns" asp-route-id="@Model.Guild.Id">Go Back</a>
    
    <hr/>
    <h4>Comments</h4>
    <div class="row">
        <div class="col">
            @*<div class="row">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <table>
                            <tr>
                                <td>
                                    <p><img src="/Debugempty.png" class="smallUserIcon"/>
                                        <code alt="000000">kate.pet</code></p>
                                </td>
                                <td rowspan="2" style="vertical-align: top; text-align: left; padding-top: 0.15rem; padding-left: 1rem;">
                                    <p>
                                        comment content
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td>3rd Dec 2024<br/>5:07pm</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>*@
            @foreach (var comment in Model.Comments.OrderBy(e => e.CreatedAt.Value))
            {
            }
        </div>
    </div>
</div>