XeniaBot.WebPanel/Models/Server/ServerBanSyncViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Discord.WebSocket;
using XeniaBot.Data.Models;

namespace XeniaBot.WebPanel.Models;

public class ServerBanSyncViewModel : BaseViewModel,
    IBanSyncBaseRecords
{
    public SocketGuildUser User { get; set; }
    public SocketGuild Guild { get; set; }
    public long BanSyncRecordCount { get; set; }
    public ulong? FilterRecordsByUserId { get; set; }
    public BanSyncStateHistoryItemModel BanSyncGuild { get; set; }
}

public interface IBanSyncBaseRecords
{
    public long BanSyncRecordCount { get; set; }
    public ulong? FilterRecordsByUserId { get; set; }
    public BanSyncStateHistoryItemModel BanSyncGuild { get; set; }
}

XeniaBot.WebPanel/Controllers/ServerBanSyncController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using XeniaBot.Data.Repositories;
using XeniaBot.Shared;
using XeniaBot.WebPanel.Helpers;
using XeniaBot.WebPanel.Models;
using XeniaBot.WebPanel.Models.Component;

namespace XeniaBot.WebPanel.Controllers;

[Controller]
public class ServerBanSyncController : BaseXeniaController
{
    private readonly ILogger<ServerController> _logger;
    public ServerBanSyncController(ILogger<ServerController> logger)
        : base()
    {
        _logger = logger;
    }

    protected async Task<ServerBanSyncViewModel> GetDetails(ulong guildId, ulong? targetUserId = null)
    {
        var data = new ServerBanSyncViewModel();
        data.Guild = _discord.GetGuild(guildId);
        data.User = data.Guild.GetUser(AspHelper.GetUserId(HttpContext) ?? 0);
        await AspHelper.FillServerModel(guildId, data, targetUserId, HttpContext);
        return data;
    }

    protected async Task<BanSyncMutualRecordsListComponentViewModel> GetComponentDetails(ulong guildId,
        int cursor,
        ulong? targetUserId)
    {
        var data = new BanSyncMutualRecordsListComponentViewModel();
        var g = _discord.GetGuild(guildId);
        data.Guild = g;
        data.User = g.GetUser(AspHelper.GetUserId(HttpContext) ?? 0);
        await AspHelper.FillServerModel(guildId, data, cursor, targetUserId, HttpContext);
        data.Cursor = cursor;
        return data;
    }
    
    [HttpGet("~/Server/{id}/BanSync")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> Index(ulong id, string? messageType = null, string? message = null, ulong? targetUserId = null)
    {
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");

        var data = await GetDetails(guild.Id, targetUserId);
        await PopulateModel(data);
        
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;

        if (!data.BanSyncGuild.Enable)
        {
            return View("NotAuthorized", new NotAuthorizedViewModel()
            {
                Message = "BanSync is not enabled on your server. <a href=\"https://xenia.kate.pet/guide/about_bansync\">More Information</a>"
            });
        }

        return View("Index", data);
    }

    [HttpGet("~/Server/{id}/BanSync/ListComponent")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> ListComponent(ulong id, int cursor = 1, ulong? targetUserId = null)
    {
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return PartialView("NotFound", "Guild not found");

        // await PopulateModel(data);
        //
        // if (!AspHelper.IsCurrentUserAdmin(this.HttpContext))
        // {
        //     data.BanSyncRecords = data.BanSyncRecords.Where(v => !v.Ghost).ToList();
        // }
        // var c = data.BanSyncRecords
        //     .OrderByDescending(v => v.Timestamp)
        //     .Skip((cursor - 1) * ServerBanSyncViewModel.PageSize)
        //     .Take(ServerBanSyncViewModel.PageSize)
        //     .ToList();
        // data.BanSyncRecords = c;
        // data.Cursor = cursor;

        var data = await GetComponentDetails(id, cursor, targetUserId);
        await PopulateModel(data);
        data.Cursor = cursor;

        if (!data.BanSyncGuild.Enable)
        {
            return PartialView("NotAuthorized", new NotAuthorizedViewModel()
            {
                Message = "BanSync is not enabled on your server. <a href=\"https://xenia.kate.pet/guide/about_bansync\">More Information</a>"
            });
        }

        return PartialView("IndexComponent", data);
    }

    [HttpGet("~/BanSync/Record/{id}/Ghost/True")]
    [AuthRequired]
    [RequireSuperuser]
    public async Task<IActionResult> GhostEnable(string id)
    {
        var banSyncInfoController = Program.Core.Services.GetRequiredService<BanSyncInfoRepository>();
        try
        {
            var record = await banSyncInfoController.GetInfo(id, true);
            if (record == null)
            {
                return PartialView("NotFound");
            }

            record.Ghost = true;
            await banSyncInfoController.SetInfo(record);
            
            var data = new BanSyncRecordViewModel()
            {
                Record = record
            };
            await PopulateModel(data);

            return PartialView("DetailsComponent", data);
        }
        catch (Exception ex)
        {
            return PartialView("Error");
        }
    }
    [HttpGet("~/BanSync/Record/{id}/Ghost/False")]
    [AuthRequired]
    [RequireSuperuser]
    public async Task<IActionResult> GhostDisable(string id)
    {
        var banSyncInfoController = Program.Core.Services.GetRequiredService<BanSyncInfoRepository>();
        try
        {
            var record = await banSyncInfoController.GetInfo(id, true);
            if (record == null)
            {
                return PartialView("NotFound");
            }

            record.Ghost = true;
            await banSyncInfoController.SetInfo(record);
            
            var data = new BanSyncRecordViewModel()
            {
                Record = record
            };
            await PopulateModel(data);

            return PartialView("DetailsComponent", data);
        }
        catch (Exception ex)
        {
            return PartialView("Error");
        }
    }
    
    [HttpGet("~/BanSync/Record/{id}")]
    [AuthRequired]
    public async Task<IActionResult> RecordInfo(string id)
    {
        var banSyncInfoController = Program.Core.Services.GetRequiredService<BanSyncInfoRepository>();
        var record = await banSyncInfoController.GetInfo(id, true);
        if (record == null)
        {
            return View("NotFound");
        }

        if (!AspHelper.IsCurrentUserAdmin(this.HttpContext) && record.Ghost)
        {
            return View("NotFound");
        }

        var data = new BanSyncRecordViewModel()
        {
            Record = record
        };
        await PopulateModel(data);

        return View("Details", data);
    }
}

XeniaBot.WebPanel/Controllers/ServerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Discord;
using Discord.WebSocket;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using XeniaBot.Data;
using XeniaBot.WebPanel.Helpers;
using XeniaBot.WebPanel.Models;
using XeniaBot.WebPanel.Models.Component;

namespace XeniaBot.WebPanel.Controllers;

[Controller]
public partial class ServerController : BaseXeniaController
{
    private readonly ILogger<ServerController> _logger;

    public ServerController(ILogger<ServerController> logger)
        : base()
    {
        _logger = logger;
    }

    [HttpGet("~/Server/{id}")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> Index(ulong id, string? messageType = null, string? message = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = await _discord.GetUserAsync((ulong)userId);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;
        
        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;
        
        return View("Details", data);
    }

    [HttpGet("~/Server/{id}/Moderation")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> ModerationView(ulong id, string? messageType = null, string? message = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = await _discord.GetUserAsync(userId.Value);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;
        
        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;
        
        return View("Details/ModerationView", data);
    }
    [HttpGet("~/Server/{id}/Fun")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> FunView(ulong id)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = await _discord.GetUserAsync(userId.Value);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;
        
        await PopulateModel(data);
        
        return View("Details/FunView", data);
    }
    
    [HttpGet("~/Server/{id}/Greeter/Join")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> GreeterJoinView(ulong id, string? messageType = null, string? message = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = await _discord.GetUserAsync(userId.Value);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;
        
        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;
        
        return View("Details/Settings/GreeterJoinView", data);
    }
    [HttpGet("~/Server/{id}/Greeter/Leave")]
    [AuthRequired]
    [RestrictToGuild(GuildIdRouteKey = "id")]
    public async Task<IActionResult> GreeterLeaveView(ulong id, string? messageType = null, string? message = null)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
            return View("NotFound", "User not found");
        var user = _discord.GetUser((ulong)userId);
        var guild = _discord.GetGuild(id);
        if (guild == null)
            return View("NotFound", "Guild not found");
        var guildUser = guild.GetUser(user.Id);

        var data = await GetDetails(guild.Id);
        data.User = guildUser;
        
        await PopulateModel(data);
        if (messageType != null)
            data.MessageType = messageType;
        if (message != null)
            data.Message = message;
        
        return View("Details/Settings/GreeterLeaveView", data);
    }
    
    [HttpGet("~/Server/")]
    [HttpGet("~/Server/List")]
    [AuthRequired]
    public async Task<IActionResult> List(ListViewStyle style = ListViewStyle.List)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
        {
            return View("NotFound", "User could not be found.");
        }
        var user = _discord.GetUser((ulong)userId);
        var data = new ServerListViewModel()
        {
            UserId = (ulong)userId,
            UserAvatar = user.GetAvatarUrl() ?? user.GetDefaultAvatarUrl()
        };

        data.Items = FilterGuildsForUser(user).ToArray();
        data.ListStyle = style;
        await PopulateModel(data);
        return View("List", data);
    }

    [HttpGet("~/Server/Components/ServerList")]
    [AuthRequired]
    public async Task<IActionResult> ListComponent(int cursor = 1, ListViewStyle style = ListViewStyle.List)
    {
        var userId = AspHelper.GetUserId(HttpContext);
        if (userId == null)
        {
            return View("NotFound", "User could not be found.");
        }
        var user = _discord.GetUser((ulong)userId);
        var data = FilterGuildsForUser(user)
            .OrderByDescending(v => v.Guild.OwnerId == v.GuildUser.Id)
            .ThenByDescending(v => v.GuildUser.GuildPermissions.Has(GuildPermission.Administrator))
            .Skip((cursor - 1) * ServerListComponentViewModel.PageSize)
            .Take(ServerListComponentViewModel.PageSize)
            .ToList();
        var model = new ServerListComponentViewModel()
        {
            Items = data,
            Cursor = cursor,
            ListStyle = style
        };
        await PopulateModel(model);
        return PartialView("ServerListComponent", model);
    }

    public List<ServerListViewModelItem> FilterGuildsForUser(SocketUser user)
    {
        var dataItems = new List<ServerListViewModelItem>();
        foreach (var item in _discord.Guilds)
        {
            var guildUser = item.GetUser(user.Id);
            if (guildUser == null)
                continue;
            if (!guildUser.GuildPermissions.ManageGuild)
                continue;
            dataItems.Add(new ServerListViewModelItem()
            {
                Guild = item,
                GuildUser = guildUser
            });
        }

        return dataItems;
    }
}

XeniaBot.WebPanel/Views/ServerBanSync/Details.cshtml
@using XeniaBot.WebPanel.Helpers
@model BanSyncRecordViewModel

@{
    ViewBag.Title = "BanSync Record";
    Layout = "_Layout";
}
@{ await Html.RenderPartialAsync("DetailsComponent"); }

XeniaBot.WebPanel/Views/ServerBanSync/DetailsComponent.cshtml
@using XeniaBot.WebPanel.Helpers
@model BanSyncRecordViewModel

<div class="container">
    <h1 class="mb-0">BanSync Record Details</h1>
    <sup>@Model.Record.RecordId</sup>
    <p>
        <img src="@(AspHelper.GetUserProfilePicture(Model.Record.UserId))"
             class="smallUserIcon" />
        <code alt="@Model.Record.UserId">@Model.Record.UserName#@Model.Record.UserDiscriminator</code>
        was banned in 
        <code alt="@Model.Record.GuildId">@Model.Record.GuildName</code>
        at
        <code>@(AspHelper.DateTimeFromTimestamp(Model.Record.Timestamp, true).ToString("yyyy/MM/dd HH:mm:ss tt"))</code>
    </p>
    <h4>Reason</h4>
    <textarea class="form-control" readonly>@Model.Record.Reason</textarea>
    @if (AspHelper.IsCurrentUserAdmin(this.Context))
    {
        <hr/>
        <label for="ghost-record">Set Ghost State</label>
        <div class="btn-group" id="host-record" role="group" aria-label="Ghost Record">
            <a class="btn btn-sm btn-outline-dark"
               hx-get="/BanSync/Record/@Model.Record.RecordId/Ghost/True"
               hx-target=".container">
                True
            </a>
            <a class="btn btn-sm btn-outline-dark"
               hx-get="/BanSync/Record/@Model.Record.RecordId/Ghost/False"
               hx-target=".container">
                False
            </a>
        </div>
    }
</div>

XeniaBot.WebPanel/Views/ServerBanSync/Index.cshtml
@using XeniaBot.Data.Models
@using XeniaBot.WebPanel.Helpers
@model ServerBanSyncViewModel

@{
    ViewBag.Title = "BanSync - " + @Model.Guild.Name;
    Layout = "_Layout";
}

<div class="d-flex flex-row align-items-center p-3 text-white rounded shadow-sm bg-dark mb-2">
    <img class="me-3 rounded-circle mr-3" src="@(Model.Guild.IconUrl ?? "/DebugEmpty.png")" alt="" width="48" height="48">
    <div class="lh-1">
        <h1 class="h6 mb-0 text-white lh-1">@Model.Guild.Name</h1>
        <small>@Model.Guild.MemberCount members &bull; @Model.BanSyncRecordCount records &bull; <a asp-controller="Server" asp-action="Index" asp-route-id="@Model.Guild.Id">Go Back</a></small>
    </div>
    
</div>
@if (Model.BanSyncRecordCount< 1)
{
    @if (@Model.FilterRecordsByUserId != null)
    {
        <div class="px-4 py-5 my-5 text-center">
            <h4>No Records Matching User were found</h4>
            <p>No records for the user provided were found.<br/>
                <a asp-controller="ServerBanSync" asp-action="Index" asp-route-id="@Model.Guild.Id" class="btn btn-outline-dark btn-sm">See All Records</a></p>
        </div>
    }
    else
    {
        <div class="px-4 py-5 my-5 text-center">
            <h4>No Records Found</h4>
            <p>No members in your server have any records in the database.</p>
        </div>
    }
}
else
{
    <table class="table table-bordered table-sm table-fs-listing" id="bansyncGuildList">
        <thead>
        <tr>
            <th>User</th>
            <th>Guild</th>
            <th>Timestamp</th>
            <th>Reason</th>
            <th></th>
        </tr>
        </thead>
        <tbody
            hx-get="/Server/@Model.Guild.Id/BanSync/ListComponent"
            hx-target="this"
            hx-swap="innerHTML"
            hx-trigger="load"
            hx-indicator=".htmx-indicator"
            id="banSyncRecordContainer">
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        <div class="spinner-border htmx-indicator" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
}

XeniaBot.WebPanel/Views/ServerBanSync/IndexComponent.cshtml
@using XeniaBot.WebPanel.Helpers
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model XeniaBot.WebPanel.Models.Component.BanSyncMutualRecordsListComponentViewModel

@foreach (var item in @Model.Items)
{
    <tr
        @{
            if (Model.IsLastPage == false && Model.IsItemLast(item))
            {
                <text>
                    hx-get="/Server/@Model.Guild.Id/BanSync/ListComponent?cursor=@(Model.Cursor + 1)"
                    hx-trigger="revealed"
                    hx-target="#banSyncRecordContainer"
                    hx-swap="beforeend"
                    hx-indicator=".htmx-indicator"</text>
        } }>
        <td>
            <img src="@(AspHelper.GetUserProfilePicture(item.UserId))"
                 class="card-img-top smallUserIcon" />
            @item.UserName#@item.UserDiscriminator
        </td>
        <td>
            <img src="@(AspHelper.GetGuildImage(item.GuildId))"
                 class="card-img-top smallUserIcon" />
            @item.GuildName
        </td>
        <td>
            @(AspHelper.DateTimeFromTimestamp(item.Timestamp, true).ToString("yyyy/MM/dd HH:mm:ss tt"))
        </td>
        <td>
            <code>
                @item.Reason.Substring(0, Math.Min(50, item.Reason.Length))
                @if (@item.Reason.Length > 50)
                {
                    <span>...</span>
                }
            </code>
        </td>
        <td>
            <a class="btn btn-secondary"
               asp-area=""
               asp-route-id="@(item.RecordId)"
               asp-controller="ServerBanSync"
               asp-action="RecordInfo"></a>
        </td>
    </tr>
}